---
minimum_pre_commit_version: 2.9.0

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # Basic config for all filetypes
  # ======
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
        exclude: .vscode/
      - id: check-toml
        stages: [pre-commit]
      - id: check-shebang-scripts-are-executable
        stages: [pre-commit]

  - repo: https://github.com/sirosen/texthooks
    rev: 869eecde9a62460e123fa60b83858fac426163e8  # frozen: 0.7.1
    hooks:
      - id: fix-smartquotes
        exclude: ^data/|\.md$
      - id: fix-spaces
        exclude: ^data/|\.md$
      - id: fix-ligatures
        exclude: ^data/|\.md$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8  # frozen: v4.4.0-pre1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # Python
  # ======
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0839f92796ae388643a08a21640a029b322be5c2  # frozen: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 6e1b55a6dbea001ba7b914eae67df3c4bbd3ff6e  # frozen: 0.10.4
    hooks:
      - id: uv-lock
        stages: [pre-commit]
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4 # frozen: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py313-plus"]
        stages: [pre-commit]
